type Query {
  folders: [Folder!]!
  folder(id: ID!): Folder
  bookmarks(
  folderId: ID
  search: String
  take: Int
  cursor: ID
): [Bookmark!]!
}

type Mutation {
  createFolder(name: String!): Folder!

  createBookmark(
    title: String!
    url: String!
    tags: [String!]!
    folderId: ID!
  ): Bookmark!

  updateBookmark(
    id: ID!
    title: String!
    url: String!
    tags: [String!]!
  ): Bookmark!

  deleteBookmark(id: ID!): Bookmark!

  moveBookmark(
    id: ID!
    folderId: ID!
  ): Bookmark!
}

type Folder {
  id: ID!
  name: String!
  createdAt: String!
  bookmarks: [Bookmark!]!
}

type Bookmark {
  id: ID!
  title: String!
  url: String!
  tags: [String!]!
  folderId: ID!
  createdAt: String!
}